apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-1.1
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: docker.io/dandycode/web-app:1.1
          ports:
            - containerPort: 5000
